[platformio]
default_envs = esp32s3usbotg

[env:esp32s3usbotg]
; build_flags = -v
framework = arduino
board = esp32s3usbotg
upload_speed = 115200
monitor_speed = 115200
platform = espressif32
; upload_protocol = espota
; upload_port = 192.168.0.255
; upload_flags =
    ; --port=8266 ; default

lib_deps =
    adafruit/Adafruit TMP117@^1.0.3
    adafruit/Adafruit LPS2X@^2.0.6

targets =
        upload
        monitor
monitor_filters =
                time
